version: "1"
name: "mcp-openai"
description: "MCP server for simple interaction with OpenAI API"

services:
  mcp-openai:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

# Smithery connection settings
connection:
  type: "mcp"
  protocol: "stdio"
  command: "node"
  args: ["dist/index.js"]
